language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - "mongodb"
before_script:
  - "cp .env.example .env"
script:
  - "npm run test:e2e"
branches:
  only:
    - master
